language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "grace-shopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: pm-grace-shopper # see README
  api_key:
    secure: N4b7B3phfoszAysfd2AItn/6yUcls7wrmbVYUiypum7XapQSUiLgpYbF2DWUIrCOSfIr7HTq9K+DD/vuowVTKktbbiQnSfKBty8cfGkTekNYHo7zGmFsvU6s7X2QzWlbZpvhQPJIGWYhKEUOOi26NGT5Q3IgiScqpdv6rnbA8VTqe12uUAMbvdy8o7v9ac5LF/89eLRjA5RKZ0mZoZpxQPB9iKC82Quv1/fj++YxXNoS/qBGp1HenvAoqyGUDiqjOTRNnjhomCOgN1ozZmxvhyzSYWacJ95pHxxHEfxhAt1RhjS9g/0MZ8zJjgKiaVjHgFdYsOSW3rCW5Q7cc/UmzkquwHUmVBnX8llvpOz1wT3OFmWJ1D6FoIAAy0MRWe61FIryUsLZLe5OSPVekI0YqcpHeN5FJR5bAEMX42IUD7f5jC07iKoPWZ6RUGH3EH4+Uspc+C4I3HSPcxHZglcyBILmKgl1IPll522lj381wtocQ5exAcnGK444IkbTCDwxSpKXTK6EfsoFncGYoHlFt2ihf1doToqabE8TYX16AKXmkVwwt8oZCpyrALKlWVkgmhz+DMyIFiXFKeK/nADGLNTC/cKPxdMg+tnuGCm7O9WF1iy0Ua5YsxkyvxczJ7S7CYZvJfaO6ui/dxwU0yojUh7RnUUALuBijKjCiVK9sU8= # see README
